### ISSUE TITLE
Urql codegen with 'typescript-operations' and no variables broken with v3

### ISSUE THREAD

**Issue by onionhammer** [FormidableLabs/urql#2622]
To reproduce:

Package.json

```json
    "@graphql-codegen/cli": "^2.11.6",
    "@graphql-codegen/typescript": "^2.7.3",
    "@graphql-codegen/typescript-operations": "^2.5.3",
    "@graphql-codegen/typescript-urql": "^3.6.4",
```

GraphQL codegen:
```
schema: schema.graphql
documents: "./src/test.graphql"
generates:
  ./src/queries.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-urql
    config:
      withHooks: true
      exportFragmentSpreadSubTypes: true
      mergeFragmentTypes: true
      scalars:
        Decimal: number
        DateTime: string
        UUID: string
```

schema.graphql

```graphql


type Environment {
  "Retrieve application version"
  version: String
}

type Query {
  "Gets current system environment"
  environment: Environment!
}

```

test.graphql

```
query env {
  environment {
    version
  }
}
```

This generates typescript with the following error:

![image](https://user-images.githubusercontent.com/969938/185679454-d6ef22c8-62b4-4c79-87f3-cab0da10e8f8.png)

const EnvDocument: DocumentNode
Argument of type '{ requestPolicy?: Urql.RequestPolicy | undefined; context?: Partial<Urql.OperationContext> | undefined; pause?: boolean | undefined; variables?: Exact<{ [key: string]: never; }> | undefined; query: DocumentNode; }' is not assignable to parameter of type 'UseQueryArgs<Exact<{ [key: string]: never; }>, EnvQuery>'.
  Type '{ requestPolicy?: Urql.RequestPolicy | undefined; context?: Partial<Urql.OperationContext> | undefined; pause?: boolean | undefined; variables?: Exact<{ [key: string]: never; }> | undefined; query: DocumentNode; }' is not assignable to type '{ variables: Exact<{ [key: string]: never; }>; }'.
    Types of property 'variables' are incompatible.
      Type 'Exact<{ [key: string]: never; }> | undefined' is not assignable to type 'Exact<{ [key: string]: never; }>'.
        Type 'undefined' is not assignable to type 'Exact<{ [key: string]: never; }>'.ts(2345)
